[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"

[de]
  languageName = "German"
  contentDir = "content/de"
  weight = 15
  [de.params]
    languageISO = "DE"
    languageTag = "de-DE"

[zh]
  languageName = "中文"
  contentDir = "content/zh"
  weight = 20
  [zh.params]
    languageISO = "ZH"
    languageTag = "zh-CN"
    titleAddition = "现代文档主题"
    description = "openkf 是一个 现代化的智能客服系统，提供企业级的ai智能客服服务"
    titleHome = "openkf 主题"
    footer = "由 <a href=\"https://www.netlify.com/\">Netlify</a>、<a href=\"https://gohugo.io/\">Hugo</a> 和 <a href=\"https://github.com/openkf/\">openkf</a> 提供支持"
    alertText = "介绍 openkf 子主题、多个 DX + UX 更新等！<a class=\"alert-link stretched-link\" href=\"https://github.com/openkf/blog/openkf-v0.2/\">查看 openkf v0.2</a>"

[nl]
  languageName = "Nederlands"
  contentDir = "content/nl"
  weight = 20
  [nl.params]
    languageISO = "NL"
    languageTag = "nl-NL"
    titleAddition = "Modern documentatie-thema"
    description = "openkf is Modern intelligent customer service system provides enterprise-level ai intelligent customer service"
    titleHome = "openkf thema"
    footer = "Mogelijk gemaakt door <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, en <a href=\"https://github.com/openkf/\">openkf</a>"
    alertText = "Introductie van het openkf-kinderthema, verschillende DX + UX-updates en meer! <a class=\"alert-link stretched-link\" href=\"https://github.com/openkf/blog/openkf-v0.2/\">Bekijk openkf v0.2</a>"
