# Meta Data for SEO

## Homepage
title = "openkf"
titleSeparator = "-"
titleAddition = "Intelligent customer service"
description = "OpenKF is an online intelligent customer service system that enhances communication and support for enterprises and open-source communities. "

## Documentation
docsVersion = "0.1"

## Open Graph
images = ["openkf.png"]
ogLocale = "en_US"
domainTLD = "openkf.netlify.app"
titleHome = "openkf website"

## Twitter Cards
twitterSite = "@xxw3293172751"
twitterCreator = "@xxw3293172751"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "openkf"
schemaAuthor = ["openkf", "openim"]
schemaAuthorTwitter = "https://twitter.com/openkf"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/cubxxw"
schemaAuthorGitHub = "https://github.com/openkf"
schemaLocale = "en-US"
schemaLogo = "logo-openkf.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "openkf.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/openkf"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/openkf/website"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://www.netlify.com/\">Netlify</a>, <a class=\"text-muted\" href=\"https://gohugo.io/\">Hugo</a>, and <a class=\"text-muted\" href=\"https://github.com/openkf/\">openkf</a>"

# Feed
copyRight = "Copyright (c) 2023-2024 Henk Verlinde"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the openkf child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://github.com/openkf/blog/openkf-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out openkf v0.2</a>"
alertText = "Introducing the openkf child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://github.com/openkf/blog/openkf-v0.2/\">Check out openkf v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/openkf/website"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["docs", "guides"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = true
  highLight = true
  kaTex = true
  multilingualMode = true
  docsVersioning = true
  fullWidth = true
  navbarSticky = true
  toTopButton = true
  scrollSpy = true # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
